#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /home
    controller: App\Controller\HomeController::welcome    controller: App\Controller\HomeController::welcome
